package com.yh.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

/**
 * @author yu
 */
public class BookAll {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book_all.book_id
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    private Integer bookId;

    @Override
    public String toString() {
        return "BookAll{" +
                       "bookId=" + bookId +
                       ", bookName='" + bookName + '\'' +
                       ", bookAuthor='" + bookAuthor + '\'' +
                       ", bookPublicationDate=" + bookPublicationDate +
                       ", bookPress='" + bookPress + '\'' +
                       ", bookIntroduce='" + bookIntroduce + '\'' +
                       ", bookPrice=" + bookPrice +
                       ", bookIsbn='" + bookIsbn + '\'' +
                       ", bookType='" + bookType + '\'' +
                       ", bookStatus='" + bookStatus + '\'' +
                       '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book_all.book_name
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    private String bookName;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book_all.book_author
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    private String bookAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book_all.book_publication_date
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    @JsonFormat(pattern = "yyyy-MM", timezone = "GMT+8")
    private Date bookPublicationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book_all.book_press
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    private String bookPress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book_all.book_introduce
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    private String bookIntroduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book_all.book_price
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    private Double bookPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book_all.book_ISBN
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    private String bookIsbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book_all.book_type
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    private String bookType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book_all.book_status
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    private String bookStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book_all.book_id
     *
     * @return the value of t_book_all.book_id
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book_all.book_id
     *
     * @param bookId the value for t_book_all.book_id
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book_all.book_name
     *
     * @return the value of t_book_all.book_name
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book_all.book_name
     *
     * @param bookName the value for t_book_all.book_name
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book_all.book_author
     *
     * @return the value of t_book_all.book_author
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    public String getBookAuthor() {
        return bookAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book_all.book_author
     *
     * @param bookAuthor the value for t_book_all.book_author
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    public void setBookAuthor(String bookAuthor) {
        this.bookAuthor = bookAuthor == null ? null : bookAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book_all.book_publication_date
     *
     * @return the value of t_book_all.book_publication_date
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    public Date getBookPublicationDate() {
        return bookPublicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book_all.book_publication_date
     *
     * @param bookPublicationDate the value for t_book_all.book_publication_date
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    public void setBookPublicationDate(Date bookPublicationDate) {
        this.bookPublicationDate = bookPublicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book_all.book_press
     *
     * @return the value of t_book_all.book_press
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    public String getBookPress() {
        return bookPress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book_all.book_press
     *
     * @param bookPress the value for t_book_all.book_press
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    public void setBookPress(String bookPress) {
        this.bookPress = bookPress == null ? null : bookPress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book_all.book_introduce
     *
     * @return the value of t_book_all.book_introduce
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    public String getBookIntroduce() {
        return bookIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book_all.book_introduce
     *
     * @param bookIntroduce the value for t_book_all.book_introduce
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    public void setBookIntroduce(String bookIntroduce) {
        this.bookIntroduce = bookIntroduce == null ? null : bookIntroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book_all.book_price
     *
     * @return the value of t_book_all.book_price
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    public Double getBookPrice() {
        return bookPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book_all.book_price
     *
     * @param bookPrice the value for t_book_all.book_price
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    public void setBookPrice(Double bookPrice) {
        this.bookPrice = bookPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book_all.book_ISBN
     *
     * @return the value of t_book_all.book_ISBN
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    public String getBookIsbn() {
        return bookIsbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book_all.book_ISBN
     *
     * @param bookIsbn the value for t_book_all.book_ISBN
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    public void setBookIsbn(String bookIsbn) {
        this.bookIsbn = bookIsbn == null ? null : bookIsbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book_all.book_type
     *
     * @return the value of t_book_all.book_type
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    public String getBookType() {
        return bookType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book_all.book_type
     *
     * @param bookType the value for t_book_all.book_type
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    public void setBookType(String bookType) {
        this.bookType = bookType == null ? null : bookType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book_all.book_status
     *
     * @return the value of t_book_all.book_status
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    public String getBookStatus() {
        return bookStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book_all.book_status
     *
     * @param bookStatus the value for t_book_all.book_status
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    public void setBookStatus(String bookStatus) {
        this.bookStatus = bookStatus == null ? null : bookStatus.trim();
    }
}