package com.yh.mapper;

import com.yh.pojo.BookAll;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
public interface BookAllMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_all
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    int deleteByPrimaryKey(Integer bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_all
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    int insert(BookAll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_all
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    BookAll selectByPrimaryKey(Integer bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_all
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    List<BookAll> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_all
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    int updateByPrimaryKey(BookAll record);
}