package com.yh.service;

import com.yh.pojo.BookAll;

import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * 作者 小豪<p>
 * 时间 2022/12/18<p>
 *
 * @author yu<p>
 */
//开启事务
@Transactional(rollbackFor = Exception.class)
public interface BookAllService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_all
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    boolean deleteByPrimaryKey(Integer bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_all
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    boolean insert(BookAll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_all
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    BookAll selectByPrimaryKey(Integer bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_all
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    List<BookAll> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_all
     *
     * @mbg.generated Mon Dec 19 09:58:54 AWST 2022
     */
    boolean updateByPrimaryKey(BookAll record);
}
